ChatAppWeb/Areas/UserAccount/Controllers/AuthController.cs
using ChatApp.UI_Library.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ChatApp.UI_Library.API.Interfaces;

namespace ChatAppWeb.Areas.UserAccount.Controllers
{
    [Area("UserAccount")]
    public class AuthController : Controller
    {
        private readonly IAuthHelper _authHelper;
        private readonly IUserHelper _userHelper;

        public AuthController(IAuthHelper authHelper, IUserHelper userHelper)
        {
            _authHelper = authHelper;
            _userHelper = userHelper;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Login(LoginModel input)
        {
            if (ModelState.IsValid)
            {
                var user = await _authHelper.Authenticate(input.Email, input.Password);

                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, user.Name),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.MobilePhone, user.PhoneNumber)
                    };

                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);

                    await HttpContext.SignInAsync(principal);
                    await _authHelper.GetUserInfo(user.Token);

                    string userId = await _userHelper.GetCurrentUserId();

                    HttpContext.Session.SetString("user_id", userId);
                    HttpContext.Session.SetString("access_token", user.Token);

                    return RedirectToAction("Index", "Home", new { area = "UserHome" });
                }

                ModelState.AddModelError(string.Empty, "Wrong Email or Password");
                return View(input);
            }
            else
            {
                return View(input);
            }
           
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Register(RegisterModel input)
        {
            if (ModelState.IsValid)
            {
                var user = await _authHelper.Register(input.Name, input.Email, input.Password, input.PhoneNumber);

                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, user.Name),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.MobilePhone, user.PhoneNumber)
                    };

                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);

                    await HttpContext.SignInAsync(principal);
                    await _authHelper.GetUserInfo(user.Token);

                    string userId = await _userHelper.GetCurrentUserId();

                    HttpContext.Session.SetString("user_id", userId);
                    HttpContext.Session.SetString("access_token", user.Token);

                    return RedirectToAction("Index", "Home", new { area = "UserHome" });
                }

                ModelState.AddModelError(string.Empty, "Something went wrong");
                return View(input);
            }
            else
            {
                return View(input);
            }
        }

        [Authorize]
        public async Task<IActionResult> LogOut()
        {
            string? userToken = HttpContext.Session.GetString("access_token");

            if (string.IsNullOrEmpty(userToken) == false)
            {
                await _authHelper.GetUserInfo(userToken);

                HttpContext.Session.Clear();

                await _authHelper.SignOut();
            }
                
            await HttpContext.SignOutAsync();

            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult GetTokenForPresenceHub()
        {
            return Json(new { success = true, token = HttpContext.Session.GetString("access_token")});
        }

    }
}

ChatAppWeb/Areas/UserHome/Controllers/GroupController.cs
using ChatApp.DataAccess.Models;
using ChatApp.UI_Library.API.Interfaces;
using ChatApp.UI_Library.Models;
using ChatApp.UI_Library.ViewModels;
using ChatAppWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ChatAppWeb.Areas.UserHome.Controllers
{
    [Area("UserHome")]
    [Authorize]
    public class GroupController : Controller
    {
        private readonly IMessageHelper _messageHelper;
        private readonly IUserHelper _userHelper;
        private readonly IGroupHelper _groupHelper;
        private readonly IAuthHelper _authHelper;
        private readonly ICacheService _cacheService;

        [BindProperty]
        public CreateGroupVM CreateGroupVM { get; set; }
        public GroupVM GroupVM { get; set; }

        public GroupController(IMessageHelper messageHelper, IUserHelper userHelper, 
            IGroupHelper groupHelper, IAuthHelper authHelper, ICacheService cacheService)
        {
            _messageHelper = messageHelper;
            _userHelper = userHelper;
            _groupHelper = groupHelper;
            _authHelper = authHelper;
            _cacheService = cacheService;
        }

        public async Task<IActionResult> Index(string channelId, string channelName)
        {
            string userToken = HttpContext.Session.GetString("access_token");
            string userId = HttpContext.Session.GetString("user_id");

            GroupVM groupVM = _cacheService.Get<GroupVM>(userId, channelId);

            if(groupVM == null)
            {
                if (string.IsNullOrEmpty(userToken) == false)
                    await _authHelper.GetUserInfo(userToken);

                var groupMessages = await _messageHelper.GetAllMessagesFromChannel(channelId, 100, 0);

                // Get recipient names
                var recipients = groupMessages
                    .DistinctBy(r => r.UserId)
                    .Select(r => r.UserName)
                    .ToList();

                groupVM = new GroupVM
                {
                    CurrentUserId = userId,
                    Channel = new ChannelModel { Id = channelId, Name = channelName, Type = "Chat" },
                    Recipients = recipients,
                    Messages = groupMessages.ToList()
                };
            }

            GroupVM = groupVM; // Populate GroupVM for Group/Index

            return View(GroupVM);
        }

        public IActionResult Create()
        {
            CreateGroupVM = new CreateGroupVM
            {
                GroupName = string.Empty,
                PhoneNumbers = new List<string>()
            };

            return View(CreateGroupVM);
        }

        [HttpPost]
        [ActionName("Create")]
        public async Task<IActionResult> CreatePOST()
        {
            if (ModelState.IsValid)
            {
                NewGroupModel result = await _groupHelper.UpsertGroup(CreateGroupVM.GroupName, CreateGroupVM.PhoneNumbers);

                // If group upsert is successful redirect to chat view => Chat/Index
                if (result != null)
                    return RedirectToAction("Index", new { result.GroupId, result.GroupName });
                else
                    return BadRequest();
            }

            return View(CreateGroupVM);
        }

        [HttpPost]
        public async Task<IActionResult> LoadMoreMessages([FromBody] LoadMessagesParams parameters)
        {
            var newMessages = await _messageHelper.GetAllMessagesFromChannel(parameters.ChannelId, 100, parameters.Messages.Count());

            return Json(new { success = true, newMessageList = newMessages.Reverse() });
        }

        [HttpPost]
        public void OnLeave([FromBody] OnLeaveGroupParams parameters)
        {
            // When leaving a page collect all messages and store in cache
            if (HttpContext.Session.IsAvailable)
            {
                parameters.GroupVM.Messages.Reverse();
                _cacheService.Set(parameters.GroupVM.CurrentUserId, parameters.GroupVM.Channel.Id, parameters.GroupVM);
                _cacheService.Set(parameters.GroupVM.CurrentUserId, "SessionChannelList", parameters.Channels);
            }
        }
    }
}

ChatAppWeb/ViewComponents/UserChatsViewComponent.cs
using ChatApp.UI_Library.API.Interfaces;
using ChatApp.UI_Library.Models;
using Microsoft.AspNetCore.Mvc;

namespace ChatAppWeb.ViewComponents
{
    public class UserChatsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(ChannelModel channel)
        {
            return View(channel);
        }
    }
}

ChatAppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChatAppWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChatAppWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-md-3 col-xl-2 px-sm-2 px-0 bg-dark min-vh-100 overflow-auto position-fixed top-0 bottom-0">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white" >

                    @if(User.Identity.IsAuthenticated)
                    {
                        <div class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none" >
                            <img src="https://placehold.co/500x500/png" class="justify-content-sm-start" style="width:30%; border-radius:50%;"/>
                            <span class="fs-5 d-none d-sm-inline ms-2">@User.Identity.Name</span>

                            <div class="dropdown">
                                <button class="btn dropdown-toggle text-white ms-5" type="button" data-bs-toggle="dropdown">
                                </button>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item nav-link" asp-area="UserHome" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item nav-link" asp-area="UserHome" asp-controller="Chat" asp-action="Create">Create Chat</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item nav-link" asp-area="UserHome" asp-controller="Group" asp-action="Create">Create Group</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item text-danger nav-link" asp-area="UserAccount" asp-controller="Auth" asp-action="LogOut">Log Out</a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <!--   Script  -->
                        <script> 
                             const hubUrl = @Json.Serialize(@Config.GetSection("AppSettings:HubUrl").Value)
                        </script>
                        <script src="~/lib/jquery/dist/jquery.min.js"></script>
                        <script src="~/js/signalr/dist/browser/signalr.js"></script>
                        
                         var userId = HttpContextAccessor.HttpContext.Session.GetString("user_id");
                         var channels = await cacheService.GetOrSetAsync<IEnumerable<ChannelModel>>(userId, "SessionChannelList", userHelper.GetAllUserChannels);
                        
                         @if (channels != null)
                         {
                              <input asp-for="@channels" value="@Html.Raw(Json.Serialize(channels))" hidden id="channelList">
                              <ul class="navbar-nav d-flex flex-column mt-1 w-100" id="channelContainer">
                                  
                                  @foreach (var channel in channels)
                                  {
                                      @await Component.InvokeAsync("UserChats", new { channel })
                                  }

                              </ul>

                              
                              <script src="~/js/presence.js"></script>
                         }

                    }
                    
                </div>
            </div>

            <div class="w-75 position-absolute bottom-0 top-0" style="left:20%">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
        
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>